version: '3.4'

services:
  mainproject:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8081:80"

  secondaryapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8082:80"

